listener 1883
listener 8883
certfile /certs/server.crt
keyfile  /certs/server.key
cafile   /certs/ca.crt
require_certificate true
allow_anonymous false
password_file /config/passwd
acl_file /config/acl
